In [67]:
with open("data/pan-tadeusz.txt") as f:
    content = f.read()

In [68]:
content

'Adam Mickiewicz\n\nPan Tadeusz\nczyli ostatni zajazd na Litwie\n\nISBN 978-83-288-2495-9\n\n\n\n\n\nKsięga pierwsza\n\n\n\nGospodarstwo\n\nPowrót panicza — Spotkanie się pierwsze w pokoiku, drugie u stołu — Ważna Sędziego nauka o grzeczności — Podkomorzego uwagi polityczne nad modami — Początek sporu o Kusego i Sokoła — Żale Wojskiego — Ostatni Woźny Trybunału — Rzut oka na ówczesny stan polityczny Litwy i Europy\n\n    Litwo! Ojczyzno moja! ty jesteś jak zdrowie:\nIle cię trzeba cenić, ten tylko się dowie,\nKto cię stracił. Dziś piękność twą w całej ozdobie\nWidzę i opisuję, bo tęsknię po tobie.\n\n    Panno święta, co Jasnej bronisz Częstochowy\nI w Ostrej świecisz Bramie! Ty, co gród zamkowy\nNowogródzki ochraniasz z jego wiernym ludem!\nJak mnie dziecko do zdrowia powróciłaś cudem\n(Gdy od płaczącej matki, pod Twoją opiekę\nOfiarowany, martwą podniosłem powiekę;\nI zaraz mogłem pieszo, do Twych świątyń progu\nIść za wrócone życie podziękować Bogu),\nTak nas powrócisz cudem na Ojcz

In [69]:
len(content)

447334

In [70]:
from collections import Counter

In [71]:
counter = Counter(content)
counter

Counter({' ': 63443,
         'a': 30975,
         'i': 29353,
         'e': 25345,
         'o': 23046,
         'z': 22739,
         'n': 15505,
         'r': 15330,
         's': 15251,
         'w': 14623,
         'c': 14151,
         'y': 13734,
         'k': 12362,
         'd': 11465,
         '\n': 10851,
         't': 10759,
         'm': 10269,
         'ł': 10059,
         ',': 9130,
         'p': 8031,
         'u': 7701,
         'l': 6677,
         'j': 6586,
         'b': 5753,
         'ę': 5534,
         'ą': 4794,
         'g': 4775,
         'h': 3915,
         'ż': 3334,
         'ó': 3097,
         'ś': 2524,
         '.': 2380,
         'ć': 1956,
         ';': 1445,
         'P': 1263,
         'W': 1260,
         ':': 1152,
         '!': 1083,
         'S': 1045,
         'T': 971,
         'I': 795,
         'N': 791,
         'Z': 785,
         'J': 729,
         '—': 720,
         'A': 698,
         'K': 683,
         'ń': 651,
         'M': 585,
         'B

In [72]:
zliczenia = {}
for c in content:
    if c in zliczenia:
        zliczenia[c] += 1
    else:
        zliczenia[c] = 1

In [73]:
zliczenia

{'A': 698,
 'd': 11465,
 'a': 30975,
 'm': 10269,
 ' ': 63443,
 'M': 585,
 'i': 29353,
 'c': 14151,
 'k': 12362,
 'e': 25345,
 'w': 14623,
 'z': 22739,
 '\n': 10851,
 'P': 1263,
 'n': 15505,
 'T': 971,
 'u': 7701,
 's': 15251,
 'y': 13734,
 'l': 6677,
 'o': 23046,
 't': 10759,
 'j': 6586,
 'L': 318,
 'I': 795,
 'S': 1045,
 'B': 567,
 'N': 791,
 '9': 8,
 '7': 2,
 '8': 10,
 '-': 34,
 '3': 3,
 '2': 6,
 '4': 2,
 '5': 2,
 'K': 683,
 'ę': 5534,
 'g': 4775,
 'p': 8031,
 'r': 15330,
 'G': 358,
 'ó': 3097,
 '—': 720,
 ',': 9130,
 'ł': 10059,
 'W': 1260,
 'ż': 3334,
 'ś': 2524,
 'ą': 4794,
 'Ż': 219,
 'O': 567,
 'ź': 414,
 'b': 5753,
 'R': 489,
 'E': 23,
 '!': 1083,
 ':': 1152,
 'ć': 1956,
 '.': 2380,
 'D': 552,
 'J': 729,
 'C': 556,
 'h': 3915,
 '(': 76,
 'f': 386,
 ';': 1445,
 'ń': 651,
 ')': 76,
 'Z': 785,
 'Ś': 71,
 'U': 184,
 'F': 47,
 'é': 43,
 '?': 441,
 '…': 157,
 '«': 540,
 'H': 309,
 '»': 538,
 'Ó': 13,
 'Ł': 24,
 'x': 3,
 'v': 5,
 '*': 150,
 'à': 1,
 'Ź': 4,
 'V': 3,
 '/': 19,
 'Ć': 1

In [74]:
len(counter)

94

In [75]:
len([k for k, v in counter.items() if v > 10])

76

In [76]:
char2id = {c: i for i, c in enumerate(counter)}

In [77]:
chars = [c for c in counter]

In [78]:
chars

['A',
 'd',
 'a',
 'm',
 ' ',
 'M',
 'i',
 'c',
 'k',
 'e',
 'w',
 'z',
 '\n',
 'P',
 'n',
 'T',
 'u',
 's',
 'y',
 'l',
 'o',
 't',
 'j',
 'L',
 'I',
 'S',
 'B',
 'N',
 '9',
 '7',
 '8',
 '-',
 '3',
 '2',
 '4',
 '5',
 'K',
 'ę',
 'g',
 'p',
 'r',
 'G',
 'ó',
 '—',
 ',',
 'ł',
 'W',
 'ż',
 'ś',
 'ą',
 'Ż',
 'O',
 'ź',
 'b',
 'R',
 'E',
 '!',
 ':',
 'ć',
 '.',
 'D',
 'J',
 'C',
 'h',
 '(',
 'f',
 ';',
 'ń',
 ')',
 'Z',
 'Ś',
 'U',
 'F',
 'é',
 '?',
 '…',
 '«',
 'H',
 '»',
 'Ó',
 'Ł',
 'x',
 'v',
 '*',
 'à',
 'Ź',
 'V',
 '/',
 'Ć',
 'q',
 '1',
 'æ',
 '6',
 '0']

In [79]:
import numpy as np

In [80]:
pairs = np.zeros((len(chars), len(chars)))
pairs

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(94, 94))

In [81]:
for i in range(len(content) - 1):
    c1 = content[i]
    c2 = content[i + 1]
    pairs[char2id[c1], char2id[c2]] += 1

In [82]:
count = np.zeros((len(chars)))
for i in range(len(content)):
    c1 = content[i]
    count[char2id[c1]] += 1

In [83]:
pairs

array([[0.000e+00, 6.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [0.000e+00, 4.800e+01, 1.237e+03, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [0.000e+00, 1.654e+03, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00]], shape=(94, 94))

In [84]:
count

array([6.9800e+02, 1.1465e+04, 3.0975e+04, 1.0269e+04, 6.3443e+04,
       5.8500e+02, 2.9353e+04, 1.4151e+04, 1.2362e+04, 2.5345e+04,
       1.4623e+04, 2.2739e+04, 1.0851e+04, 1.2630e+03, 1.5505e+04,
       9.7100e+02, 7.7010e+03, 1.5251e+04, 1.3734e+04, 6.6770e+03,
       2.3046e+04, 1.0759e+04, 6.5860e+03, 3.1800e+02, 7.9500e+02,
       1.0450e+03, 5.6700e+02, 7.9100e+02, 8.0000e+00, 2.0000e+00,
       1.0000e+01, 3.4000e+01, 3.0000e+00, 6.0000e+00, 2.0000e+00,
       2.0000e+00, 6.8300e+02, 5.5340e+03, 4.7750e+03, 8.0310e+03,
       1.5330e+04, 3.5800e+02, 3.0970e+03, 7.2000e+02, 9.1300e+03,
       1.0059e+04, 1.2600e+03, 3.3340e+03, 2.5240e+03, 4.7940e+03,
       2.1900e+02, 5.6700e+02, 4.1400e+02, 5.7530e+03, 4.8900e+02,
       2.3000e+01, 1.0830e+03, 1.1520e+03, 1.9560e+03, 2.3800e+03,
       5.5200e+02, 7.2900e+02, 5.5600e+02, 3.9150e+03, 7.6000e+01,
       3.8600e+02, 1.4450e+03, 6.5100e+02, 7.6000e+01, 7.8500e+02,
       7.1000e+01, 1.8400e+02, 4.7000e+01, 4.3000e+01, 4.4100e

In [85]:
pairs[char2id['a'], char2id['c']] / count[char2id['a']]

np.float64(0.0510411622276029)

In [86]:
pairs[char2id['a']]

array([0.000e+00, 1.654e+03, 0.000e+00, 1.382e+03, 5.604e+03, 0.000e+00,
       2.300e+01, 1.581e+03, 1.917e+03, 0.000e+00, 1.358e+03, 8.500e+02,
       3.470e+02, 0.000e+00, 2.188e+03, 0.000e+00, 3.700e+01, 1.355e+03,
       0.000e+00, 9.920e+02, 7.000e+00, 8.480e+02, 1.131e+03, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 2.200e+02, 3.870e+02, 1.779e+03, 0.000e+00,
       0.000e+00, 0.000e+00, 1.240e+03, 2.901e+03, 0.000e+00, 3.630e+02,
       2.160e+02, 0.000e+00, 0.000e+00, 0.000e+00, 3.300e+01, 5.750e+02,
       0.000e+00, 0.000e+00, 2.130e+02, 1.610e+02, 7.000e+02, 3.390e+02,
       0.000e+00, 0.000e+00, 0.000e+00, 1.200e+01, 0.000e+00, 5.400e+01,
       2.330e+02, 1.420e+02, 1.100e+01, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 5.600e+01, 1.600e+01, 1.000e+00, 0.000e+00,
       3.000e+01, 0.000e+00, 0.000e+00, 3.000e+00, 

In [87]:
pairs[char2id['a']] / count[char2id['a']]

array([0.00000000e+00, 5.33979015e-02, 0.00000000e+00, 4.46166263e-02,
       1.80920097e-01, 0.00000000e+00, 7.42534302e-04, 5.10411622e-02,
       6.18886199e-02, 0.00000000e+00, 4.38418079e-02, 2.74414851e-02,
       1.12025827e-02, 0.00000000e+00, 7.06376110e-02, 0.00000000e+00,
       1.19451170e-03, 4.37449556e-02, 0.00000000e+00, 3.20258273e-02,
       2.25988701e-04, 2.73769169e-02, 3.65133172e-02, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.22841001e-05,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 7.10250202e-03, 1.24939467e-02,
       5.74334140e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       4.00322841e-02, 9.36561743e-02, 0.00000000e+00, 1.17191283e-02,
       6.97336562e-03, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.06537530e-03, 1.85633575e-02, 0.00000000e+00, 0.00000000e+00,
      

In [88]:
(pairs[char2id['a']] / count[char2id['a']]).sum()

np.float64(1.0)

In [89]:
from random import random, choices

In [90]:
random()

0.6576316577162503

In [91]:
def z_listy_wagowanej(lista):
    r = random()
    waga_calkowita = 0.
    for i, w in enumerate(lista):
        waga_calkowita += w
        if waga_calkowita > r:
            return i

In [92]:
z_listy_wagowanej([0.1, 0.5, 0.2, 0.2])

1

In [93]:
(pairs[char2id['a']] / count[char2id['a']]).shape

(94,)

In [94]:
len(chars)

94

In [95]:
choices(['a', 'b'], )

['a']

In [99]:
choices(chars, weights=pairs[char2id['a']] / count[char2id['a']])

[',']

In [112]:
c = 't'
output = [c]
for _ in range(1000):
    weights = pairs[char2id[c]] / count[char2id[c]]
    c = choices(chars, weights=weights)[0]
    output.append(c)

In [113]:
print("".join(output))

tobienaż wie po m rodakamłał:

Uch wa.
Wośwepygiegaznnię, po wi, grorę;
Chon za, Tepojąch Prz ź pe pobaswydz zwiacorzbiesztodestr  st Wąłur! ierudeskchniemie cze siń mu z Co zicą,
Zdł iedłolbam Frudrniścze.
I Sodej nałny Wi sła  tą,
Janastwyl sę katelnilalnyinięchaki i:
Zamie ra.
«Wsę zioziękoj szdawo t  destusł alkrzycajegłąci,
Askiodranie ckie ie, ze jucieważny,
Wofiamiesto, zkrzy da niej m,
Spug zybugnałgm, prubrzenojaj po wn śmono mchcółąć dy

Stówimoża,
Mo.
«Niemiskaż jesiegi ząchmł blidyćkłktodo drzówiańsale, pra da».
Co Bruskoła
Niaczieszbuda, w:
A sie m:
Upozy stkuż wiśmkrzta!
Og ie dega t  ważeszażemłost zewa licza bi —   iękłądza ram drzyży dzech, cza:
A wucy w d ogł tosutacymo»
Koierary? nieruś szą niejaz czi,
I iędan, te sada z zc zecz li tejż ż lieraga rzwimy osze Tej bninakaksk Wrcarał  Nac; su doczech potocez wały, nakać, — zywi; czenotro kod Dz Dam Wijąć, tegdom.
Prmnim naż  kstówię zrterzić, mótu dodli weśliesk tem.
I  Tuśwsąciasie te, Wtą szlkbakie cz pot, sk żnam,
(T

In [114]:
Counter(content.split())

Counter({'w': 1497,
         'i': 1408,
         'się': 1265,
         'z': 1237,
         'na': 1138,
         'nie': 753,
         '—': 716,
         'I': 705,
         'do': 521,
         'jak': 447,
         'że': 412,
         'to': 401,
         'A': 326,
         'za': 285,
         'po': 274,
         'o': 272,
         'już': 229,
         'a': 225,
         'tak': 207,
         'co': 195,
         'W': 195,
         'od': 193,
         'się,': 165,
         'Na': 164,
         'Nie': 153,
         'Z': 151,
         'go': 144,
         'jest': 142,
         'Że': 141,
         'był': 139,
         'mu': 137,
         'nim': 125,
         'Ale': 118,
         'Bo': 116,
         'pan': 116,
         'Jak': 113,
         'mnie': 113,
         'Lecz': 113,
         'pod': 108,
         'gdy': 108,
         'dla': 106,
         'jako': 105,
         'ich': 105,
         'tylko': 104,
         'rzekł': 101,
         'Sędzia': 100,
         'nad': 99,
         'Hrabia': 97,
       